language: java
jdk:
        - oraclejdk9
notifications:
    email: false

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7347b1501d9dca8c5355
    on_success: change
    on_failure: always
    on_start: never
